version: '3'
services:
  db:
    image: postgres
  web:
    image: blog-web
    working_dir: /app
    # command: sleep 10000
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - db